server:
  port: 8888
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE

#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    user:
      name: wpp
      password: wpp
    oauth2:
      client:
        provider:
          iotdevpp:
            authorization-uri: http://localhost:53020/uaa/oauth/authorize
            token-uri: http://localhost:53020/uaa/oauth/token
            userInfoUri: http://localhost:53020/uaa/user
            userNameAttribute: username
        registration:
          github:
            client-id: Iv1.731affdf509af8ef
            client-secret: da4f753b4081f4ba909bfb59428e2ea23968f504
          iotdev:
            provider: iotdevpp
            client-id: c2
            client-secret: c1
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8888/login/oauth2/code/iotdev
            scope: api
            clientName: AAA

debug: true
management:
  endpoints:
    web:
      exposure:
        include: mappings,beans
#          iotdev:
#            provider: iotdev
#            client-id: f8X40VBsCa6b8cr4IWDY3AiroKwa
#            client-secret: AAXatT4U6adeBvnNjgcEbVVL3Nca
#            clientAuthenticationMethod: post
#            authorizationGrantType: authorization_code
#            redirectUri: http://localhost:8080/login/oauth2/code/iotdev/
#            scope: perm:users:details
#            clientName: iotdev-client
#          okta:
#            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
#            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
#            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo

#            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys