spring:
  application:
    name: cloud-zuul
server:
  port: 2103
#
#  配置zuul的路由跳转
zuul:
  #  同一前缀
  prefix: /rest
  routes:
    #    微服务名-别名路由
    cloud-eureka-order:
      path: /order-service/**
      #将你的服务转发到我网关的本地接口上
      url: forward:/local
    #     路径路由
    user:
      path: /user/**
      url: http://localhost:8080/
    order:
      path: /order/**
      url: http://localhost:8081/
    api:
      path: /api/**
      url: forward:/local
  #      禁用过滤器
  BlackIPFilter:
    pre:
      disable: true
  #开启重试机制
  retryable: true
ribbon:
  #  请求超时时间
  connectTimeout: 500
  #  请求处理时间
  readTimeout: 5000
  #  最大重试次数
  maxAutoRetries: 1
  #  切换实例的最大重试次数
  maxAutoRetriesNextServer: 3
  #  对所有操作都进行重试
  okToRetryOnAllOperations: true
  #  对执行的Http码重试
  retryableStatusCodes: 500,404,502
ip:
  filter:
    black: 127.0.0.1,0.0.0.0
    white: 8.8.8.8,88.88.88.88
#    注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetch-registry: true
    register-with-eureka: true
#测试开启选项
filter:
  test:
    passvalue: false
    blocking: false
    error: false
#重试配置