spring:
  application:
    name: cloud-zuul
server:
  port: 2103
#
#  配置zuul的路由跳转
zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:8080/
    order:
      path: /order/**
      url: http://localhost:8081/
#    注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetch-registry: true
    register-with-eureka: true
